"""sessions media structured

Revision ID: 0002
Revises: 0001
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=True),
    sa.Column('choices', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('required_items', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('missing_information', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('urgency', sa.String(length=16), nullable=True),
    sa.Column('diy_allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_messages_session_id'), 'session_messages', ['session_id'], unique=False)
    op.create_table('session_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['session_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_actions_session_id'), 'session_actions', ['session_id'], unique=False)
    op.create_table('session_hypotheses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['session_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_hypotheses_message_id'), 'session_hypotheses', ['message_id'], unique=False)
    op.create_table('session_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['session_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_observations_message_id'), 'session_observations', ['message_id'], unique=False)
    op.create_table('session_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['session_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_verifications_session_id'), 'session_verifications', ['session_id'], unique=False)
    op.add_column('diagnostic_sessions', sa.Column('current_state', sa.String(length=32), nullable=False, server_default='awaiting_analysis'))
    op.add_column('diagnostic_sessions', sa.Column('title', sa.String(length=120), nullable=True))
    op.add_column('diagnostic_sessions', sa.Column('category', sa.String(length=32), nullable=True))
    op.add_column('diagnostic_sessions', sa.Column('subcategory', sa.String(length=120), nullable=True))
    op.add_column('diagnostic_sessions', sa.Column('risk_level', sa.String(length=16), nullable=True))
    op.alter_column('diagnostic_sessions', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.drop_column('diagnostic_sessions', 'last_analysis')
    op.add_column('media_assets', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('exif_stripped', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_column('users', 'account_id')
    op.drop_column('media_assets', 'exif_stripped')
    op.drop_column('media_assets', 'height')
    op.drop_column('media_assets', 'width')
    op.add_column('diagnostic_sessions', sa.Column('last_analysis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('diagnostic_sessions', 'status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('diagnostic_sessions', 'risk_level')
    op.drop_column('diagnostic_sessions', 'subcategory')
    op.drop_column('diagnostic_sessions', 'category')
    op.drop_column('diagnostic_sessions', 'title')
    op.drop_column('diagnostic_sessions', 'current_state')
    op.drop_index(op.f('ix_session_verifications_session_id'), table_name='session_verifications')
    op.drop_table('session_verifications')
    op.drop_index(op.f('ix_session_observations_message_id'), table_name='session_observations')
    op.drop_table('session_observations')
    op.drop_index(op.f('ix_session_hypotheses_message_id'), table_name='session_hypotheses')
    op.drop_table('session_hypotheses')
    op.drop_index(op.f('ix_session_actions_session_id'), table_name='session_actions')
    op.drop_table('session_actions')
    op.drop_index(op.f('ix_session_messages_session_id'), table_name='session_messages')
    op.drop_table('session_messages')
    # ### end Alembic commands ###
