"""video media

Revision ID: 0003
Revises: 0002
"""
import sqlalchemy as sa
from alembic import op

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_frames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('t_seconds', sa.Float(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_video_frames_media_id'), 'video_frames', ['media_id'], unique=False)
    op.add_column('media_assets', sa.Column('duration_s', sa.Float(), nullable=True))
    op.add_column('media_assets', sa.Column('has_audio', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'has_audio')
    op.drop_column('media_assets', 'duration_s')
    op.drop_index(op.f('ix_video_frames_media_id'), table_name='video_frames')
    op.drop_table('video_frames')
    # ### end Alembic commands ###
